version: '3.4'

services:
  aspnetcore6webapp1:
    image: aspnetcore6webapp1
    build:
      context: .
      dockerfile: AspNetCore6WebApp1/Dockerfile
    depends_on:
            - db
   
  db:
    image: "mcr.microsoft.com/mssql/server"
    environment:
        SA_PASSWORD: "Your_password123"
        ACCEPT_EULA: "Y"